apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
  annotations:
    co.elastic.logs/enabled: "true"
    co.elastic.logs/json.keys_under_root: "true"
    co.elastic.logs/json.ignore_decoding_error: "true"
    co.elastic.logs/json.overwrite_keys: "true"
    co.elastic.logs/json.add_error_key: "true"
    co.elastic.logs/json.expand_keys: "true"
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: todo
  strategy:
    type: Recreate 
  template: 
    metadata: 
      labels: 
        app: todo
      annotations:
        co.elastic.logs/enabled: "true"
        co.elastic.logs/json.keys_under_root: "true"
        co.elastic.logs/json.ignore_decoding_error: "true"
        co.elastic.logs/json.overwrite_keys: "true"
        co.elastic.logs/json.add_error_key: "true"
        co.elastic.logs/json.expand_keys: "true"
    spec: 
      containers:
        - name: todo
          image: aborgesrodrigues/todo
          imagePullPolicy: Never
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1000m"    
          env:
            - name: CONN_STRING
              value: postgres://postgres:example@postgres:5432/todo?sslmode=disable
            - name: AUDITLOG_S3_BUCKET
              value: "wcf-audit-local"
            - name: AUDITLOG_S3_DIRECTORY
              value: "todo-api/"
            - name: AUDITLOG_S3_ENDPOINT
              value: "http://localstack:4566"
            - name: AUDITLOG_S3_REGION
              value: "us-east-1"
            - name: AWS_ACCESS_KEY_ID
              value: "test"
            - name: AWS_SECRET_ACCESS_KEY
              value: "test"
            - name: AWS_SESSION_TOKEN
              value: "test"
          ports:
            - containerPort: 8080
              name: todo                                            
