version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: local.Dockerfile
    ports:
      - 8080:8080
    environment:
      CONN_STRING: postgres://postgres:example@db:5432/todo?sslmode=disable
    volumes:
      - .:/build/
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: todo
    healthcheck:
      test: [“CMD-SHELL”, “pg_isready”]
      interval    : 1s
      timeout: 5s
      retries: 10
    volumes:
      - ./data:/var/lib/postgresql/data
