version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./dev/docker/local.Dockerfile
    ports:
      - 8080:8080
    environment:
      CONN_STRING: host=host.docker.internal user=pguser password=pguser dbname=todo port=5432 sslmode=disable
      AUDITLOG_S3_BUCKET: "audit-local"
      AUDITLOG_S3_DIRECTORY: "todo-api/"
      AUDITLOG_S3_ENDPOINT: "http://localstack:4566"
      AUDITLOG_S3_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"
      AWS_SESSION_TOKEN: "test"
      JWT_SECRET_KEY: g2ZWQUjt6csyUTgDmMEZqmG3Dz9gWENFX@AuLwVppKgW@@6jtQ7@FJGbuL!R9xxfQkj8Y@8tj!eq2@u*nxgVC*62sC!sWT3BwjZT
    labels:
        co.elastic.logs/enabled: true
        co.elastic.logs/json.keys_under_root: true
        co.elastic.logs/json.ignore_decoding_error: true
        co.elastic.logs/json.overwrite_keys: true
        co.elastic.logs/json.add_error_key: true
        co.elastic.logs/json.expand_keys: true
    volumes:
      - .:/build/
    depends_on:
      db:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
      localstack:
        condition: service_healthy
  db:
    image: postgres:13-alpine3.18
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: todo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
    volumes:
      - ./dev/db/initial.sql:/docker-entrypoint-initdb.d/initial.sql
  filebeat:
    user: root
    image: docker.elastic.co/beats/filebeat:7.14.0
    command: filebeat -e -strict.perms=false
    volumes:
      - ./dev/filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./dev/filebeat/elasticsearch-ca.pem:/usr/share/filebeat/certs/elasticsearch-ca.pem
  elasticsearch:
    labels:
      co.elastic.logs/enabled: false
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    volumes:
      - ./dev/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./dev/elasticsearch/http.p12:/usr/share/elasticsearch/config/certs/http.p12
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "-k", "https://localhost:9200/_cat/health"]
      interval: 3s
      timeout: 3s
      retries: 80
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.0
    volumes:
      - ./dev/kibana/kibana.docker.yml:/usr/share/kibana/config/kibana.yml
      - ./dev/kibana/elasticsearch-ca.pem:/usr/share/kibana/certs/elasticsearch-ca.pem
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "-k", "http://localhost:5601/api/status"]
      interval: 3s
      timeout: 3s
      retries: 80
    ports:
      - 5601:5601
  localstack:
    image: localstack/localstack:1.4.0
    environment:
      SERVICES: s3
    ports:
      - "4566:4566"
    volumes:
      - ./dev/localstack:/docker-entrypoint-initaws.d

# TODO check https://github.com/swimlane/elk-tls-docker