apiVersion: v1
kind: ConfigMap
metadata:
  name: s3-bucket-creation-script
data: 
  create-resource.sh: |-
    echo "Creating AWS resources..."
    export AWS_ACCESS_KEY_ID=test
    export AWS_SECRET_ACCESS_KEY=test

    aws --debug --endpoint-url=http://localstack:4566 s3api create-bucket --bucket audit-local