apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate 
  template: 
    metadata: 
      labels: 
        app: postgres
    spec: 
      containers:
        - name: postgres
          image: postgres:13-alpine3.18
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1000m"
          env:
            - name: POSTGRES_USER
              value: pguser
            - name: POSTGRES_PASSWORD
              value: pguser
            - name: POSTGRES_DB
              value: todo
          ports:
            - containerPort: 5432
              name: postgres    
          volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgresql/data    
            - name: dbcreation-script
              mountPath: /docker-entrypoint-initdb.d #https://hub.docker.com/_/mysql Refer Initializing a fresh instance                                            
      volumes: 
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: storage-class-pv-claim
        - name: dbcreation-script
          configMap:
            name: dbcreation-script