apiVersion: v1
kind: Service
metadata: 
  name: postgres
spec:
  # type: NodePort # TODO remove when changing do clusterIP
  selector:
    app: postgres 
  ports: 
    - port: 5432  
  clusterIP: None # This means we are going to use Pod IP    