apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  strategy:
    type: Recreate 
  template: 
    metadata: 
      labels: 
        app: kibana
    spec: 
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.14.0
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          ports:
            - containerPort: 5601
              name: kibana                                            
