filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      # only containers with co.elastic.logs/enabled: true will be discovered
      hints.default_config.enabled: false
output.elasticsearch:
  hosts: ["https://elasticsearch:9200"] 
  username: "elastic"
  password: "changeme"
  protocol: "https"
  ssl.verification_mode: "none"
  ssl.certificate_authorities: ["/usr/share/filebeat/certs/elasticsearch-ca.pem"]
setup.kibana:
  host: "kibana:5601"