filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      # only containers with co.elastic.logs/enabled: true will be discovered
      hints.default_config.enabled: false
output.elasticsearch:
  hosts: ["https://elasticsearch:9200"] 
  username: "elastic"
  password: "changeme"
  ssl.certificate_authorities: ["/usr/share/filebeat/config/ca.crt"]
  ssl.certificate: "/usr/share/filebeat/config/filebeat.crt"
  ssl.key: "/usr/share/filebeat/config/filebeat.key"
setup.kibana:
  host: "kibana:5601"