apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  strategy:
    type: Recreate 
  template: 
    metadata: 
      labels: 
        app: elasticsearch
    spec: 
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          env:
            - name: discovery.type
              value: single-node
          ports:
            - containerPort: 9200
              name: elasticsearch                                            
